### ISSUE TITLE
arr.end() TypeError: undefined is not a function

### ISSUE THREAD

**Issue by unlight** [thedufer/JSONStreamify#11]
Running example from readme, getting error `TypeError: undefined is not a function`.
`arr.end` - is undefined, did you you mean `arr.finish()`?
**Node v0.12.0**

**Comment by thedufer** [comment]
Oops!  I expected I'd get notified about new issues.  Sorry this is delayed.

It looks like I forgot to cut a new release.  The docs are correct for the current version in the repo, but not the current version in npm.

**Comment by thedufer** [comment]
Published a new version.  Please install it again and you should get what the docs are describing.
