### ISSUE TITLE
Bug when streaming utf-8

### ISSUE THREAD

**Issue by dpatti** [thedufer/JSONStreamify#5]
You can't naively stringify chunks of a stream as utf-8. You don't know if you're going to receive a chunk in the middle of a utf-8 code point. Example:

``` javascript
var b1 = Buffer([0x62, 0xe2]);
var b2 = Buffer([0x80, 0x93, 0x61, 0x72]);

var f = new stream.PassThrough();
// Expected: b–ar
f.pipe(process.stdout);
f.write(b1);
f.write(b2);
f.end();

var o = new ObjectStream();
// Actual: b���ar
o.pipe(process.stdout);
o.write("foo", f);
o.finish();
```

**Comment by thedufer** [comment]
How reasonable is it to assume that a buffer stream is UTF-8?

**Comment by thedufer** [comment]
Note to self: http://debuggable.com/posts/streaming-utf-8-with-node-js:4bf28e8b-a290-432f-a222-11c1cbdd56cb

**Comment by dpatti** [comment]
One alternative would be to _not_ do the stringification yourself, but to provide a transform stream for the user where they could specify their encoding. So like:

``` javascript
var o = new ObjectStream();
o.write("foo", utf16Stream.pipe(new SanitizeTransform('utf16le')));
```

And then maybe if they don't use the transform, you use it internally with utf-8 as the sensible default.

**Comment by thedufer** [comment]
Ooooh here's a lib that does the transforms - https://www.npmjs.com/package/iconv-lite

`decodeStream('utf8')`, for example, creates a transform that expects a buffer stream to be piped in and yields a string stream.  It appears to handle the character split across chunks case correctly, too.  I'll just send streams through that if they try to give me buffers.

**Comment by dpatti** [comment]
Do you _need_ to do that if you're still just assuming utf-8? There is still a 1-to-1 mapping of characters you must escape to bytes. For example, `0x0A` is always `\n` no matter where it shows up in a utf-8 byte array.

**Comment by thedufer** [comment]
Need to?  No.  But I don't want to be responsible for either finding multibyte character markers or escaping all of the right things.  I could probably get it right, but I might get it subtly wrong and kill someone or something.  Is there a compelling reason to not do this?

**Comment by dpatti** [comment]
Extra overhead from having to convert bytes -> characters, extra dependencies. Neither are major. That, and, it almost seems smarter to not use a butchered `JSON.stringify` and instead follow the json spec.
